Repository PICode-Team/PICode, pull requests merged in 2021-10, with the labels that each got.

#37 Return noteId when create note
  src/module/data/service/notespace/noteManager.ts
Labels: bug

#39 Update note socket to move note path (Close #32)
  package-lock.json
  package.json
  src/lib/interval.ts
  src/module/data/service/calendar/calendarManager.ts
  src/module/data/service/chatspace/chatManager.ts
  src/module/data/service/codespace/codeManager.ts
  src/module/data/service/codespace/terminalManager.ts
  src/module/data/service/etc/fileManager.ts
  src/module/data/service/issuespace/issueManager.ts
  src/module/data/service/issuespace/kanbanManager.ts
  src/module/data/service/issuespace/milestoneManager.ts
  src/module/data/service/notespace/noteManager.ts
  src/module/data/service/workspace/dockerManager.ts
  src/module/data/service/workspace/workspaceManager.ts
  src/module/merge.ts
  src/module/socket/code.ts
  src/module/socket/note.ts
  src/module/socket/service/alarm/alarm.ts
  src/module/socket/service/calendar/calendar.ts
  src/module/socket/service/chatspace/chat.ts
  src/module/socket/service/codespace/code.ts
  src/module/socket/service/codespace/terminal.ts
  src/module/socket/service/etc/etc.ts
  src/module/socket/service/etc/manager.ts
  src/module/socket/service/etc/user.ts
  src/module/socket/service/etc/work.ts
  src/module/socket/service/issuespace/issue.ts
  src/module/socket/service/issuespace/kanban.ts
  src/module/socket/service/issuespace/milestone.ts
  src/module/socket/service/notespace/note.ts
  src/module/socket/socket.ts
  src/route/docker/docker.ts
  src/route/index.ts
  src/route/openGraph/index.ts
  src/route/openGraph/openGraph.ts
  src/types/module/data/service/notespace/note.types.ts
Labels: bug, enhancement

#41 Correct spelling NoteSpace -> noteSpace (Close #40)
  src/lib/interval.ts
  src/module/data/service/workspace/dockerManager.ts
Labels: bug, enhancement

#48 Fixed bugs
  src/lib/router/token.ts
  src/module/data/codespace/codeManager.ts
  src/module/merge.ts
Labels: bug

#49 Add workspace create, get test code
  src/lib/interval.ts
  src/module/data/workspace/dockerManager.ts
  src/module/data/workspace/workspaceManager.ts
  src/types/module/data/service/workspace/workspace.type.ts
  test/testConstant.ts
  test/unit/service/user.test.ts
  test/unit/service/workspace.test.ts
Labels: enhancement

#51 Update docker command logic (#50)
  src/module/data/workspace/dockerManager.ts
Labels: enhancement

#56 Fix Bug when creating workspace(Close #55)
  src/module/data/workspace/dockerManager.ts
  src/module/socket/service/notespace/note.ts
Labels: bug, enhancement
